# Generated by Django 5.2 on 2025-05-02 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsclip', '0007_alter_article_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Escolha um dia qualquer do mês')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsclip.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClippingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_type', models.CharField(choices=[('release', 'Release'), ('artigo', 'Artigo'), ('nota', 'Nota'), ('post', 'Post'), ('espontaneo', 'Espontâneo')], max_length=20)),
                ('media_channel', models.CharField(choices=[('impresso', 'Impresso'), ('tv', 'TV'), ('radio', 'Rádio'), ('social', 'Redes Sociais'), ('site', 'Site')], max_length=20)),
                ('valor_cm', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Valoração (cm)')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='reports/screenshots/')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsclip.article')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reports_app.reportconfig')),
            ],
        ),
    ]
