# Generated by Django 4.2.21 on 2025-05-28 00:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0008_client_instagram_client_x_client_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='excluded',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Excluído manualmente'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tópico'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='newsclip_ar_search__13326d_gin'),
        ),
    ]
