# Generated by Django 4.2.21 on 2025-05-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0009_article_search_vector_alter_article_excluded_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Tópico'),
        ),
    ]
