# Generated by Django 5.2.8 on 2025-11-20 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0010_alter_article_options_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Fonte')),
                ('url', models.URLField(max_length=500, verbose_name='URL do Feed/Site')),
                ('source_type', models.CharField(choices=[('RSS', 'RSS Feed'), ('SCRAPE', 'Web Scrape'), ('API', 'API (NewsAPI/NewsData)')], default='RSS', max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('title_selector', models.CharField(blank=True, max_length=200, null=True, verbose_name='Seletor de Título (CSS)')),
                ('link_selector', models.CharField(blank=True, max_length=200, null=True, verbose_name='Seletor de Link (CSS)')),
                ('date_selector', models.CharField(blank=True, max_length=200, null=True, verbose_name='Seletor de Data (CSS)')),
            ],
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('SUCCESS', 'Sucesso')], default='INFO', max_length=20, verbose_name='Nível')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='newsclip.client')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsclip.source')),
            ],
        ),
    ]
