# Generated by Django 4.2.26 on 2026-04-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0011_source_fetchlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteudo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excluded',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Excluido manualmente'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Publicacao'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Topico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='domains',
            field=models.TextField(blank=True, help_text='Ex: g1.globo.com, uol.com.br', verbose_name='Dominios confiaveis (virgula-separados)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='keywords',
            field=models.TextField(help_text='Separe por virgulas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, verbose_name='YouTube (canal/usuario)'),
        ),
        migrations.AlterField(
            model_name='fetchlog',
            name='level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('SUCCESS', 'Sucesso')], default='INFO', max_length=20, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='source',
            name='title_selector',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Seletor de Titulo (CSS)'),
        ),
    ]
