# Generated by Django 5.2.15 on 2026-06-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0015_source_discovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('RUNNING', 'Em execucao'), ('SUCCESS', 'Concluida'), ('PARTIAL', 'Parcial'), ('ERROR', 'Erro')], db_index=True, default='RUNNING', max_length=20)),
                ('queries_count', models.PositiveIntegerField(default=0)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('relevant_count', models.PositiveIntegerField(default=0)),
                ('articles_count', models.PositiveIntegerField(default=0)),
                ('new_sources_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_runs', to='newsclip.client')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'provider', '-started_at'], name='newsclip_di_client__ff5f7b_idx')],
            },
        ),
    ]
