# Generated by Django 5.2.15 on 2026-06-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0018_article_quality_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='context_terms',
            field=models.TextField(blank=True, help_text='Separe por virgulas. Ex: rodeio, arena, ingressos, show, evento.', verbose_name='Termos de contexto'),
        ),
        migrations.AddField(
            model_name='client',
            name='name_variations',
            field=models.TextField(blank=True, help_text='Separe por virgulas. Ex: Country Bulls, Rio Preto Bulls, @perfiloficial.', verbose_name='Variacoes do nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='keywords',
            field=models.TextField(blank=True, help_text='Campo legado. Estes termos sao tratados como contexto, nao como identidade forte.', verbose_name='Termos complementares'),
        ),
        migrations.CreateModel(
            name='NewsFetchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('running', 'Em execucao'), ('completed', 'Concluida'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], db_index=True, default='queued', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('result_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_jobs', to='newsclip.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status', '-created_at'], name='newsclip_ne_client__022bef_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelevanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, db_index=True, max_length=50)),
                ('query', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('url', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('relevance_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('relevance_reason', models.CharField(blank=True, max_length=255)),
                ('decision', models.CharField(choices=[('APPROVED', 'Aprovado'), ('REVIEW', 'Revisao'), ('REJECTED', 'Rejeitado')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevance_audit_logs', to='newsclip.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'decision', '-created_at'], name='newsclip_re_client__7efd89_idx')],
            },
        ),
    ]
