# Generated by Django 5.2.15 on 2026-07-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0019_client_context_terms_client_name_variations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='context_terms',
            field=models.TextField(blank=True, help_text='Separe por virgulas. Ex: cidade, setor, cargo, evento, produto ou tema relacionado.', verbose_name='Termos de contexto'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name_variations',
            field=models.TextField(blank=True, help_text='Separe por virgulas. Ex: nome abreviado, apelido publico, nome com cargo, @perfiloficial.', verbose_name='Variacoes do nome'),
        ),
    ]
