# Generated by Django 5.2.15 on 2026-07-09 22:16

from django.db import migrations


def _normalize_model_sources(model, canonicalize_source_name, include_url=False):
    pending = []
    selected_fields = ["id", "source"] + (["url"] if include_url else [])
    for record in model.objects.only(*selected_fields).iterator(chunk_size=500):
        url = record.url if include_url else ""
        canonical_name = canonicalize_source_name(record.source, url)
        if not canonical_name or canonical_name == record.source:
            continue
        record.source = canonical_name
        pending.append(record)
        if len(pending) >= 500:
            model.objects.bulk_update(pending, ["source"], batch_size=500)
            pending.clear()

    if pending:
        model.objects.bulk_update(pending, ["source"], batch_size=500)


def normalize_existing_sources(apps, schema_editor):
    from newsclip.utils import canonicalize_source_name

    Article = apps.get_model("newsclip", "Article")
    RelevanceAuditLog = apps.get_model("newsclip", "RelevanceAuditLog")
    _normalize_model_sources(Article, canonicalize_source_name, include_url=True)
    _normalize_model_sources(RelevanceAuditLog, canonicalize_source_name, include_url=True)


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0020_alter_client_context_terms_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_existing_sources, migrations.RunPython.noop),
    ]
