# Generated by Django 5.2.15 on 2026-07-10 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0021_normalize_source_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Validada'), ('REVIEW', 'Revisar'), ('REJECTED', 'Rejeitada')], db_index=True, max_length=16)),
                ('base_status', models.CharField(blank=True, max_length=16)),
                ('base_score', models.PositiveSmallIntegerField(default=0)),
                ('base_reason', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_feedback', to='newsclip.article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_feedback', to='newsclip.client')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['client', 'decision', '-updated_at'], name='newsclip_va_client__552933_idx')],
            },
        ),
    ]
