# Generated by Django 5.2.15 on 2026-07-10 12:07

from django.db import migrations


def backfill_manual_feedback(apps, schema_editor):
    Article = apps.get_model("newsclip", "Article")
    ValidationFeedback = apps.get_model("newsclip", "ValidationFeedback")
    pending = []
    # Nao usa excluded=True: migracoes antigas tambem excluiam duplicatas
    # automaticamente, e esses registros contaminariam o dataset humano.
    articles = Article.objects.filter(
        validation_reason__icontains="usuario"
    ).iterator(chunk_size=500)

    for article in articles:
        if article.excluded or article.validation_status == "REJECTED":
            decision = "REJECTED"
        elif article.validation_status == "REVIEW":
            decision = "REVIEW"
        else:
            decision = "ACCEPTED"
        pending.append(
            ValidationFeedback(
                article_id=article.pk,
                client_id=article.client_id,
                decision=decision,
                base_status=article.validation_status,
                base_score=max(0, min(int(article.relevance_score or 0), 100)),
                base_reason=(article.validation_reason or "")[:255],
                title=(article.title or "")[:500],
                content=(article.content or article.summary or "")[:4000],
                source=(article.source or "")[:255],
                provider=(article.provider or "")[:32],
            )
        )
        if len(pending) >= 500:
            ValidationFeedback.objects.bulk_create(pending, batch_size=500, ignore_conflicts=True)
            pending.clear()

    if pending:
        ValidationFeedback.objects.bulk_create(pending, batch_size=500, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("newsclip", "0022_validation_feedback_learning"),
    ]

    operations = [
        migrations.RunPython(backfill_manual_feedback, migrations.RunPython.noop),
    ]
