"""Catálogo canônico de dimensões, eixos e indicadores municipais.

Este módulo é deliberadamente livre de dependências do Django. Ele concentra os
identificadores estáveis usados pela sincronização, API e importações de dados.
Os 64 indicadores dos eixos 1 a 16 reproduzem o escopo do documento de
referência. Os quatro indicadores de cada eixo 17 a 22 são propostas técnicas e
estão identificados como tal em ``description`` e ``methodology``.
"""


DEFAULT_FREQUENCY = "annual"


DIMENSIONS = (
    {
        "name": "Cidade que Funciona",
        "slug": "cidade-que-funciona",
        "description": "Gestão pública eficiente, transparente, digital e orientada a resultados.",
        "accent_color": "#146C94",
        "icon_name": "building-government",
        "display_order": 1,
    },
    {
        "name": "Cidade que Cuida",
        "slug": "cidade-que-cuida",
        "description": "Saúde, assistência social, habitação e cuidado com as pessoas.",
        "accent_color": "#2A9D8F",
        "icon_name": "heart-pulse",
        "display_order": 2,
    },
    {
        "name": "Cidade que Protege",
        "slug": "cidade-que-protege",
        "description": "Segurança, mobilidade segura, direitos e inclusão.",
        "accent_color": "#3A506B",
        "icon_name": "shield",
        "display_order": 3,
    },
    {
        "name": "Cidade que se Transforma",
        "slug": "cidade-que-se-transforma",
        "description": "Obras, zeladoria, saneamento e sustentabilidade urbana.",
        "accent_color": "#E76F51",
        "icon_name": "city",
        "display_order": 4,
    },
    {
        "name": "Cidade que Gera Oportunidades",
        "slug": "cidade-que-gera-oportunidades",
        "description": "Emprego, qualificação, empreendedorismo e desenvolvimento econômico.",
        "accent_color": "#F4A261",
        "icon_name": "briefcase",
        "display_order": 5,
    },
    {
        "name": "Cidade que Inspira",
        "slug": "cidade-que-inspira",
        "description": "Educação, cultura e esporte como vetores de desenvolvimento humano.",
        "accent_color": "#7B2CBF",
        "icon_name": "sparkles",
        "display_order": 6,
    },
)


AXES = (
    {
        "number": 1,
        "dimension_slug": "cidade-que-funciona",
        "name": "Eficiência fiscal e orçamentária",
        "slug": "eficiencia-fiscal-orcamentaria",
        "description": "Autonomia, rigidez, investimento, liquidez e resultado das contas municipais.",
    },
    {
        "number": 2,
        "dimension_slug": "cidade-que-funciona",
        "name": "Transparência e atendimento ao cidadão",
        "slug": "transparencia-atendimento-cidadao",
        "description": "Transparência ativa e passiva, acesso à informação e resolutividade da Ouvidoria.",
    },
    {
        "number": 3,
        "dimension_slug": "cidade-que-cuida",
        "name": "Tempo de espera e acesso à saúde",
        "slug": "tempo-espera-acesso-saude",
        "description": "Filas reguladas, prazos e acesso efetivo a consultas, exames e tratamentos.",
    },
    {
        "number": 4,
        "dimension_slug": "cidade-que-cuida",
        "name": "Produção da rede municipal de saúde",
        "slug": "producao-rede-municipal-saude",
        "description": "Produção da atenção primária, especializada, de urgência e por teleatendimento.",
    },
    {
        "number": 5,
        "dimension_slug": "cidade-que-cuida",
        "name": "Atendimento socioassistencial",
        "slug": "atendimento-socioassistencial",
        "description": "Cobertura e capacidade de resposta dos serviços e benefícios socioassistenciais.",
    },
    {
        "number": 6,
        "dimension_slug": "cidade-que-cuida",
        "name": "Regularização fundiária e habitação",
        "slug": "regularizacao-fundiaria-habitacao",
        "description": "Titulação, produção habitacional, melhorias e duração dos processos.",
    },
    {
        "number": 7,
        "dimension_slug": "cidade-que-protege",
        "name": "Segurança pública municipal",
        "slug": "seguranca-publica-municipal",
        "description": "Resposta operacional da GCM, prevenção e resultados de segurança no território.",
    },
    {
        "number": 8,
        "dimension_slug": "cidade-que-protege",
        "name": "Mobilidade e transporte coletivo",
        "slug": "mobilidade-transporte-coletivo",
        "description": "Uso, regularidade e pontualidade do transporte e segurança no trânsito.",
    },
    {
        "number": 9,
        "dimension_slug": "cidade-que-se-transforma",
        "name": "Execução de obras",
        "slug": "execucao-obras",
        "description": "Execução física, financeira e cumprimento de prazos da carteira municipal de obras.",
    },
    {
        "number": 10,
        "dimension_slug": "cidade-que-se-transforma",
        "name": "Zeladoria urbana",
        "slug": "zeladoria-urbana",
        "description": "Resolutividade, prazo, produção física e qualidade dos serviços de zeladoria.",
    },
    {
        "number": 11,
        "dimension_slug": "cidade-que-gera-oportunidades",
        "name": "Geração de empregos",
        "slug": "geracao-empregos",
        "description": "Evolução do emprego formal e efetividade dos serviços municipais de colocação.",
    },
    {
        "number": 12,
        "dimension_slug": "cidade-que-gera-oportunidades",
        "name": "Qualificação profissional",
        "slug": "qualificacao-profissional",
        "description": "Ocupação, conclusão e resultados profissionais da qualificação oferecida.",
    },
    {
        "number": 13,
        "dimension_slug": "cidade-que-inspira",
        "name": "Desempenho da educação",
        "slug": "desempenho-educacao",
        "description": "Aprendizagem, aprovação, abandono e adequação entre idade e série.",
    },
    {
        "number": 14,
        "dimension_slug": "cidade-que-inspira",
        "name": "Atendimento da Educação Especial",
        "slug": "atendimento-educacao-especial",
        "description": "Cobertura e capacidade de atendimento educacional especializado e apoio escolar.",
    },
    {
        "number": 15,
        "dimension_slug": "cidade-que-inspira",
        "name": "Participação cultural",
        "slug": "participacao-cultural",
        "description": "Acesso, distribuição territorial e uso da infraestrutura e dos programas culturais.",
    },
    {
        "number": 16,
        "dimension_slug": "cidade-que-inspira",
        "name": "Atendimento esportivo",
        "slug": "atendimento-esportivo",
        "description": "Participação, permanência, cobertura e uso dos equipamentos esportivos.",
    },
    {
        "number": 17,
        "dimension_slug": "cidade-que-se-transforma",
        "name": "Saneamento e qualidade da água",
        "slug": "saneamento-qualidade-agua",
        "description": "Cobertura e desempenho dos serviços de água, esgoto e controle de qualidade.",
    },
    {
        "number": 18,
        "dimension_slug": "cidade-que-se-transforma",
        "name": "Meio ambiente e arborização",
        "slug": "meio-ambiente-arborizacao",
        "description": "Cobertura verde, arborização e recuperação ambiental no território municipal.",
    },
    {
        "number": 19,
        "dimension_slug": "cidade-que-gera-oportunidades",
        "name": "Desenvolvimento econômico e empreendedorismo",
        "slug": "desenvolvimento-economico-empreendedorismo",
        "description": "Dinamismo empresarial, formalização e atividade econômica local.",
    },
    {
        "number": 20,
        "dimension_slug": "cidade-que-funciona",
        "name": "Inovação e transformação digital",
        "slug": "inovacao-transformacao-digital",
        "description": "Digitalização dos serviços públicos e fortalecimento do ecossistema de inovação.",
    },
    {
        "number": 21,
        "dimension_slug": "cidade-que-protege",
        "name": "Proteção dos direitos e inclusão",
        "slug": "protecao-direitos-inclusao",
        "description": "Resposta a violações de direitos, acessibilidade e alcance das políticas de inclusão.",
    },
    {
        "number": 22,
        "dimension_slug": "cidade-que-funciona",
        "name": "Valorização e desempenho dos servidores",
        "slug": "valorizacao-desempenho-servidores",
        "description": "Capacidade, desenvolvimento, engajamento e desempenho da força de trabalho municipal.",
    },
)


AXIS_DEFAULT_SOURCES = {
    1: "IFGF e IEG-M",
    2: "CGU e Escala Brasil Transparente",
    3: "Regulação municipal e e-Gestor APS",
    4: "DATASUS, SIA/SUS e SIOPS",
    5: "Censo SUAS, RMA e CadÚnico",
    6: "Secretaria Municipal de Habitação e Ministério das Cidades",
    7: "Guarda Civil Municipal e Sinesp",
    8: "Secretaria Municipal de Trânsito, Ministério das Cidades e Senatran",
    9: "Secretaria Municipal de Obras e Painel de Obras do TCESP",
    10: "Sistema municipal de zeladoria, SINISA e IEG-M",
    11: "Novo Caged e serviço municipal de emprego",
    12: "Programa municipal de qualificação, Inep e Monitor de Profissões",
    13: "Secretaria Municipal de Educação e Inep",
    14: "Secretaria Municipal de Educação e Censo Escolar",
    15: "Secretaria Municipal de Cultura e SNIIC",
    16: "Secretaria Municipal de Esportes e Ministério do Esporte",
    17: "Serviço municipal de saneamento e SINISA",
    18: "Secretaria Municipal de Meio Ambiente",
    19: "Secretaria Municipal de Desenvolvimento Econômico",
    20: "Secretaria Municipal responsável por inovação e governo digital",
    21: "Rede municipal de proteção de direitos",
    22: "Secretaria Municipal de Administração",
}


def _indicator(
    axis_number,
    slug,
    name,
    description,
    methodology,
    unit,
    *,
    polarity="neutral",
    frequency=DEFAULT_FREQUENCY,
    source_name=None,
    kind="mandatory",
):
    return {
        "axis_number": axis_number,
        "slug": slug,
        "name": name,
        "description": description,
        "methodology": methodology,
        "unit": unit,
        "polarity": polarity,
        "frequency": frequency,
        "source_name": source_name or AXIS_DEFAULT_SOURCES[axis_number],
        "kind": kind,
    }


def _proposed(axis_number, slug, name, description, methodology, unit, **kwargs):
    return _indicator(
        axis_number,
        slug,
        name,
        f"Proposta técnica para o novo eixo: {description}",
        f"Proposta técnica; validar fórmula, fonte, periodicidade e responsável antes da homologação. {methodology}",
        unit,
        kind="technical_proposal",
        **kwargs,
    )


def _supplemental(axis_number, slug, name, description, methodology, unit, **kwargs):
    return _indicator(
        axis_number,
        slug,
        name,
        description,
        methodology,
        unit,
        kind="supplemental",
        **kwargs,
    )


MANDATORY_INDICATORS = (
    # Eixo 1
    _indicator(
        1,
        "participacao-receita-propria-receita-corrente",
        "Participação da receita própria na receita corrente",
        "Mostra quanto o Município financia com arrecadação própria e sua dependência de transferências.",
        "Receitas tributárias e próprias ÷ receita corrente × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        1,
        "despesa-pessoal-receita-corrente-liquida",
        "Despesa com pessoal sobre a Receita Corrente Líquida",
        "Mede o comprometimento e a rigidez do orçamento com despesas de pessoal.",
        "Despesa total com pessoal ÷ Receita Corrente Líquida × 100.",
        "%",
        polarity="lower",
    ),
    _indicator(
        1,
        "investimentos-liquidados-receita-corrente-liquida",
        "Investimentos liquidados sobre a Receita Corrente Líquida",
        "Mede quanto da capacidade financeira virou obras, equipamentos e infraestrutura.",
        "Investimentos liquidados ÷ Receita Corrente Líquida × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        1,
        "disponibilidade-caixa-liquida",
        "Disponibilidade de caixa líquida",
        "Mede a capacidade de cumprir compromissos sem deixar despesas descobertas.",
        "Disponibilidade de caixa menos obrigações financeiras e restos a pagar.",
        "R$",
        polarity="higher",
    ),
    # Eixo 2
    _indicator(
        2,
        "indice-transparencia-ativa",
        "Índice de transparência ativa",
        "Percentual de itens obrigatórios publicados e atualizados no Portal da Transparência.",
        "Itens publicados e atualizados ÷ total de itens avaliados × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        2,
        "pedidos-acesso-informacao-respondidos-prazo",
        "Pedidos de acesso à informação respondidos dentro do prazo",
        "Mede o cumprimento do prazo nos pedidos concluídos de acesso à informação.",
        "Pedidos respondidos no prazo ÷ total de pedidos concluídos × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        2,
        "tempo-medio-resposta-pedidos-informacao",
        "Tempo médio de resposta aos pedidos de informação",
        "Tempo corrido médio de resposta; registrar também a mediana para reduzir distorções.",
        "Média dos dias corridos entre protocolo e resposta final, acompanhada da mediana.",
        "dias",
        polarity="lower",
    ),
    _indicator(
        2,
        "taxa-resolucao-ouvidoria",
        "Taxa de resolução da Ouvidoria",
        "Mede a proporção de manifestações recebidas que foram concluídas.",
        "Manifestações concluídas ÷ manifestações recebidas × 100.",
        "%",
        polarity="higher",
    ),
    # Eixo 3
    _indicator(
        3,
        "tempo-mediano-espera-consulta-especializada",
        "Tempo mediano de espera para consulta especializada",
        "Espera entre solicitação regulada e atendimento, no geral e nas cinco especialidades mais demoradas.",
        "Mediana dos dias entre solicitação regulada e atendimento; detalhar as cinco maiores esperas.",
        "dias",
        polarity="lower",
        frequency="monthly",
    ),
    _indicator(
        3,
        "tempo-mediano-espera-exames",
        "Tempo mediano de espera para exames",
        "Espera por exames laboratoriais, de imagem e de maior complexidade.",
        "Mediana dos dias entre solicitação regulada e realização, com detalhamento por categoria.",
        "dias",
        polarity="lower",
        frequency="monthly",
    ),
    _indicator(
        3,
        "pacientes-fila-espera",
        "Quantidade de pacientes na fila de espera",
        "Estoque de pacientes aguardando consultas, exames, cirurgias, terapias ou tratamentos.",
        "Contagem na data de corte, detalhada por tipo; registrar o encerramento anual e cortes intermediários.",
        "pacientes",
        polarity="lower",
        frequency="monthly",
    ),
    _indicator(
        3,
        "pacientes-atendidos-dentro-prazo",
        "Percentual de pacientes atendidos dentro do prazo definido pela Secretaria",
        "Mede o cumprimento do prazo assistencial definido para cada serviço.",
        "Pacientes atendidos dentro do prazo ÷ total de pacientes atendidos × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    # Eixo 4
    _indicator(
        4,
        "atendimentos-atencao-primaria-mil-habitantes",
        "Atendimentos da Atenção Primária por mil habitantes",
        "Produção da Atenção Primária, detalhada por atendimento médico, enfermagem, odontologia e ACS.",
        "Atendimentos da Atenção Primária ÷ população × 1.000.",
        "por 1.000 hab.",
        polarity="neutral",
        frequency="monthly",
    ),
    _indicator(
        4,
        "atendimentos-especializados-mil-habitantes",
        "Atendimentos e procedimentos especializados por mil habitantes",
        "Produção dos centros, laboratórios, CAPS, CER, Saúde da Mulher e demais serviços especializados.",
        "Atendimentos e procedimentos especializados ÷ população × 1.000.",
        "por 1.000 hab.",
        polarity="neutral",
        frequency="monthly",
    ),
    _indicator(
        4,
        "atendimentos-urgencia-emergencia-mil-habitantes",
        "Atendimentos de urgência e emergência por mil habitantes",
        "Produção de urgência e emergência, detalhada por UPA e pronto-socorro.",
        "Atendimentos de urgência e emergência ÷ população × 1.000.",
        "por 1.000 hab.",
        polarity="neutral",
        frequency="monthly",
    ),
    _indicator(
        4,
        "teleconsultas-realizadas",
        "Teleconsultas realizadas",
        "Volume de teleconsultas e sua participação na Atenção Primária.",
        "Registrar total, valor por mil habitantes, crescimento anual e percentual das consultas da Atenção Primária.",
        "teleconsultas",
        polarity="neutral",
        frequency="monthly",
    ),
    # Eixo 5
    _indicator(
        5,
        "familias-acompanhadas-paif",
        "Famílias acompanhadas pelo PAIF",
        "Famílias em acompanhamento, novas inclusões e acompanhamentos encerrados.",
        "Contagem de famílias, com detalhamento da situação do acompanhamento no período.",
        "famílias",
        polarity="neutral",
        frequency="monthly",
    ),
    _indicator(
        5,
        "atendimentos-cras-creas",
        "Atendimentos realizados nos CRAS e CREAS",
        "Volume de atendimentos e intensidade em relação às famílias inscritas no CadÚnico.",
        "Registrar o total e calcular atendimentos ÷ famílias inscritas no CadÚnico × 1.000.",
        "atendimentos",
        polarity="neutral",
        frequency="monthly",
    ),
    _indicator(
        5,
        "taxa-atualizacao-cadunico",
        "Taxa de atualização do CadÚnico",
        "Mede a atualização cadastral dentro do prazo aplicável.",
        "Cadastros atualizados dentro do prazo ÷ total sujeito à atualização × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    _indicator(
        5,
        "tempo-primeiro-atendimento-socioassistencial",
        "Tempo médio para o primeiro atendimento socioassistencial",
        "Espera entre solicitação ou encaminhamento e o atendimento inicial.",
        "Média dos dias entre solicitação ou encaminhamento e primeiro atendimento.",
        "dias",
        polarity="lower",
        frequency="monthly",
    ),
    # Eixo 6
    _indicator(
        6,
        "titulos-propriedade-entregues",
        "Matrículas ou títulos de propriedade entregues",
        "Entrega anual de matrículas ou títulos e famílias beneficiadas.",
        "Contagem de documentos efetivamente entregues no período, com famílias beneficiadas no detalhamento.",
        "títulos",
        polarity="higher",
    ),
    _indicator(
        6,
        "unidades-habitacionais-entregues",
        "Unidades habitacionais entregues",
        "Unidades efetivamente entregues; acompanhar separadamente o estoque em outras fases.",
        "Contagem das unidades entregues; detalhar concluídas, em construção, contratadas e planejadas.",
        "unidades",
        polarity="higher",
    ),
    _indicator(
        6,
        "familias-beneficiadas-regularizacao-melhoria",
        "Famílias beneficiadas por regularização ou melhoria habitacional",
        "Famílias alcançadas por titulação, reforma, acessibilidade ou correção de insalubridade.",
        "Contagem única de famílias beneficiadas no período, detalhada por modalidade.",
        "famílias",
        polarity="higher",
    ),
    _indicator(
        6,
        "tempo-medio-processo-regularizacao",
        "Tempo médio do processo de regularização",
        "Duração entre abertura do processo e registro da matrícula.",
        "Média dos meses transcorridos entre abertura e registro da matrícula.",
        "meses",
        polarity="lower",
    ),
    # Eixo 7
    _indicator(
        7,
        "tempo-medio-resposta-gcm",
        "Tempo médio de resposta da Guarda Civil Municipal",
        "Tempo entre acionamento e chegada, separado entre ocorrências prioritárias e não prioritárias.",
        "Média dos minutos entre o acionamento e a chegada da equipe.",
        "minutos",
        polarity="lower",
        frequency="monthly",
    ),
    _indicator(
        7,
        "taxa-atendimento-ocorrencias-gcm",
        "Taxa de atendimento das ocorrências recebidas",
        "Proporção dos acionamentos recebidos que foram atendidos pela GCM.",
        "Ocorrências atendidas ÷ ocorrências recebidas × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    _indicator(
        7,
        "cobertura-preventiva-escolas-equipamentos",
        "Cobertura preventiva de escolas e equipamentos municipais",
        "Cobertura regular de patrulhamento nas unidades municipais prioritárias.",
        "Unidades com patrulhamento regular ÷ total de unidades prioritárias × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    _indicator(
        7,
        "ocorrencias-criminais-selecionadas-100-mil",
        "Taxa de ocorrências criminais selecionadas por 100 mil habitantes",
        "Resultado territorial para crimes selecionados; não representa desempenho exclusivo da GCM.",
        "Ocorrências selecionadas ÷ população × 100.000, detalhadas por natureza criminal.",
        "por 100 mil hab.",
        polarity="lower",
        frequency="monthly",
    ),
    # Eixo 8
    _indicator(
        8,
        "passageiros-transportados",
        "Passageiros transportados",
        "Demanda do transporte coletivo, incluindo usuários da Tarifa Zero.",
        "Registrar total anual, média diária, passageiros por habitante e usuários da Tarifa Zero.",
        "passageiros",
        polarity="neutral",
        frequency="monthly",
    ),
    _indicator(
        8,
        "cumprimento-viagens-programadas",
        "Índice de cumprimento das viagens programadas",
        "Mede a execução da oferta de viagens planejada.",
        "Viagens realizadas ÷ viagens programadas × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    _indicator(
        8,
        "pontualidade-transporte-coletivo",
        "Índice de pontualidade do transporte coletivo",
        "Mede o cumprimento da tolerância de horário nas viagens monitoradas.",
        "Viagens dentro da tolerância ÷ viagens monitoradas × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    _indicator(
        8,
        "mortes-transito-100-mil-habitantes",
        "Mortes no trânsito por 100 mil habitantes",
        "Mortalidade decorrente de sinistros de trânsito no território.",
        "Mortes no trânsito ÷ população × 100.000.",
        "por 100 mil hab.",
        polarity="lower",
    ),
    # Eixo 9
    _indicator(
        9,
        "execucao-fisica-obras",
        "Percentual de execução física das obras",
        "Avanço físico por obra e consolidado da carteira.",
        "Etapas físicas executadas ÷ etapas físicas previstas × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    _indicator(
        9,
        "execucao-financeira-obras",
        "Percentual de execução financeira",
        "Proporção do valor contratado atualizado que já foi liquidada.",
        "Valor liquidado ÷ valor contratado atualizado × 100.",
        "%",
        polarity="neutral",
        frequency="monthly",
    ),
    _indicator(
        9,
        "obras-dentro-prazo",
        "Obras dentro do prazo",
        "Participação das obras em execução que permanecem no cronograma.",
        "Obras dentro do cronograma ÷ total de obras em execução × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    _indicator(
        9,
        "obras-atrasadas-paralisadas",
        "Obras atrasadas ou paralisadas",
        "Estoque de obras com atraso ou paralisação e sua relevância na carteira.",
        "Registrar quantidade, valor contratado, percentual da carteira e média de dias de atraso.",
        "obras",
        polarity="lower",
        frequency="monthly",
    ),
    # Eixo 10
    _indicator(
        10,
        "resolucao-solicitacoes-zeladoria",
        "Taxa de resolução das solicitações de zeladoria",
        "Resolutividade dos pedidos de roçada, poda, limpeza, tapa-buraco e manutenção.",
        "Ordens de serviço concluídas ÷ ordens recebidas × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    _indicator(
        10,
        "tempo-medio-atendimento-zeladoria",
        "Tempo médio de atendimento",
        "Tempo entre abertura e conclusão de solicitações de zeladoria.",
        "Média dos dias entre abertura da solicitação e conclusão da ordem.",
        "dias",
        polarity="lower",
        frequency="monthly",
    ),
    _indicator(
        10,
        "producao-fisica-servicos-zeladoria",
        "Produção física dos serviços",
        "Produção de roçada, vias, resíduos, poda e manutenção de estradas rurais.",
        "Registrar cada serviço em sua unidade: m², km, toneladas ou árvores; manter o tipo no detalhamento.",
        "unidades diversas",
        polarity="neutral",
        frequency="monthly",
    ),
    _indicator(
        10,
        "taxa-reincidencia-zeladoria",
        "Taxa de reincidência",
        "Mede locais que exigiram novo atendimento dentro do prazo de controle.",
        "Locais com novo atendimento no prazo definido ÷ locais atendidos × 100.",
        "%",
        polarity="lower",
        frequency="monthly",
    ),
    # Eixo 11
    _indicator(
        11,
        "saldo-empregos-formais",
        "Saldo de empregos formais",
        "Diferença entre admissões e desligamentos, no total e por setor econômico.",
        "Admissões menos desligamentos.",
        "postos de trabalho",
        polarity="higher",
        frequency="monthly",
    ),
    _indicator(
        11,
        "crescimento-estoque-empregos-formais",
        "Crescimento do estoque de empregos formais",
        "Variação percentual do estoque de vínculos formais.",
        "((Estoque final menos estoque inicial) ÷ estoque inicial) × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        11,
        "trabalhadores-colocados-servico-municipal",
        "Trabalhadores colocados pelo serviço municipal de emprego",
        "Pessoas efetivamente contratadas após atendimento pelo Balcão de Empregos ou PAT.",
        "Contagem de trabalhadores com contratação confirmada no período.",
        "trabalhadores",
        polarity="higher",
        frequency="monthly",
    ),
    _indicator(
        11,
        "taxa-colocacao-servico-municipal",
        "Taxa de colocação do serviço municipal",
        "Efetividade dos encaminhamentos feitos pelo serviço municipal.",
        "Trabalhadores contratados ÷ trabalhadores encaminhados × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    # Eixo 12
    _indicator(
        12,
        "ocupacao-vagas-qualificacao",
        "Taxa de ocupação das vagas de qualificação",
        "Proporção das vagas ofertadas que resultaram em matrícula.",
        "Matrículas realizadas ÷ vagas oferecidas × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        12,
        "conclusao-cursos-qualificacao",
        "Taxa de conclusão dos cursos",
        "Proporção dos matriculados que concluíram a formação.",
        "Concluintes ÷ matriculados × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        12,
        "insercao-profissional-pos-formacao",
        "Taxa de inserção profissional após a formação",
        "Concluintes empregados ou empreendendo em até 180 dias.",
        "Concluintes empregados ou empreendendo em até 180 dias ÷ concluintes acompanhados × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        12,
        "cursos-vinculados-demanda-identificada",
        "Percentual de cursos vinculados a ocupações com demanda identificada",
        "Alinhamento da oferta de cursos às vagas e aos setores em expansão.",
        "Cursos ligados a vagas e setores em expansão ÷ total de cursos oferecidos × 100.",
        "%",
        polarity="higher",
    ),
    # Eixo 13
    _indicator(
        13,
        "alunos-aprendizagem-adequada",
        "Percentual de alunos com aprendizagem adequada",
        "Aprendizagem adequada em Língua Portuguesa e Matemática, por etapa avaliada.",
        "Percentual conforme avaliação municipal anual ou avaliação estadual/federal disponível, detalhado por disciplina e etapa.",
        "%",
        polarity="higher",
    ),
    _indicator(
        13,
        "taxa-aprovacao",
        "Taxa de aprovação",
        "Proporção dos alunos com resultado final que foram aprovados.",
        "Alunos aprovados ÷ alunos com resultado final × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        13,
        "taxa-abandono",
        "Taxa de abandono",
        "Proporção das matrículas consideradas que terminaram em abandono.",
        "Alunos que abandonaram ÷ matrículas consideradas × 100.",
        "%",
        polarity="lower",
    ),
    _indicator(
        13,
        "distorcao-idade-serie",
        "Taxa de distorção idade-série",
        "Percentual de alunos com idade acima da recomendada para a etapa, por rede e etapa.",
        "Aplicar a fórmula oficial do Inep e detalhar por etapa e rede.",
        "%",
        polarity="lower",
    ),
    # Eixo 14
    _indicator(
        14,
        "cobertura-atendimento-educacional-especializado",
        "Cobertura do Atendimento Educacional Especializado",
        "Proporção dos alunos elegíveis matriculados que recebem AEE.",
        "Alunos elegíveis atendidos pelo AEE ÷ alunos elegíveis matriculados × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        14,
        "tempo-implantacao-apoio-educacional",
        "Tempo médio para implantação do apoio necessário",
        "Tempo entre identificação formal da necessidade e início do atendimento ou disponibilização do profissional.",
        "Média dos dias entre identificação formal e implantação efetiva do apoio.",
        "dias",
        polarity="lower",
        frequency="monthly",
    ),
    _indicator(
        14,
        "alunos-por-professor-aee",
        "Relação de alunos por professor de AEE",
        "Carga média de alunos atendidos por professor, detalhada por escola ou núcleo.",
        "Alunos atendidos pelo AEE ÷ professores de AEE.",
        "alunos/professor",
        polarity="neutral",
    ),
    _indicator(
        14,
        "alunos-necessitam-apoio-por-profissional",
        "Relação de alunos que necessitam de apoio por profissional disponível",
        "Demanda de apoio escolar em relação à disponibilidade de profissionais.",
        "Alunos com apoio necessário ÷ profissionais de apoio.",
        "alunos/profissional",
        polarity="lower",
    ),
    # Eixo 15
    _indicator(
        15,
        "publico-acoes-culturais",
        "Público participante das ações culturais",
        "Alcance das ações culturais no total e em métricas relativas.",
        "Registrar público total, por mil habitantes, por evento e participantes únicos quando possível.",
        "participantes",
        polarity="higher",
    ),
    _indicator(
        15,
        "cobertura-territorial-programacao-cultural",
        "Cobertura territorial da programação",
        "Proporção das regiões administrativas alcançadas por programação cultural.",
        "Regiões administrativas atendidas ÷ total de regiões × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        15,
        "ocupacao-equipamentos-culturais",
        "Taxa de ocupação dos equipamentos culturais",
        "Utilização da agenda disponível nos equipamentos culturais.",
        "Dias ou horários com programação ÷ dias ou horários disponíveis × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        15,
        "artistas-agentes-culturais-beneficiados",
        "Artistas e agentes culturais beneficiados",
        "Pessoas contratadas, premiadas, contempladas por editais ou participantes de formação.",
        "Contagem única de beneficiados, detalhada por modalidade.",
        "pessoas",
        polarity="higher",
    ),
    # Eixo 16
    _indicator(
        16,
        "pessoas-atendidas-programas-esportivos",
        "Pessoas atendidas regularmente em programas esportivos",
        "Participantes únicos, por mil habitantes e por grupo etário.",
        "Contagem de participantes únicos com atendimento regular; detalhar crianças, adolescentes, adultos e idosos.",
        "participantes",
        polarity="higher",
    ),
    _indicator(
        16,
        "frequencia-permanencia-programas-esportivos",
        "Taxa de frequência ou permanência",
        "Proporção dos matriculados que atingiu a frequência mínima definida.",
        "Participantes com frequência mínima ÷ matriculados × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        16,
        "cobertura-territorial-nucleos-esportivos",
        "Cobertura territorial dos núcleos esportivos",
        "Proporção das regiões alcançadas pelos núcleos esportivos.",
        "Regiões atendidas ÷ total de regiões × 100.",
        "%",
        polarity="higher",
    ),
    _indicator(
        16,
        "utilizacao-equipamentos-esportivos",
        "Taxa de utilização dos equipamentos esportivos",
        "Uso efetivo da capacidade horária dos equipamentos.",
        "Horas efetivamente utilizadas ÷ horas disponíveis × 100.",
        "%",
        polarity="higher",
    ),
)


PROPOSED_INDICATORS = (
    # Eixo 17
    _proposed(
        17,
        "cobertura-abastecimento-agua",
        "Cobertura do abastecimento de água",
        "parcela da população atendida por rede de abastecimento de água.",
        "População atendida por abastecimento de água ÷ população total × 100.",
        "%",
        polarity="higher",
    ),
    _proposed(
        17,
        "cobertura-coleta-esgoto",
        "Cobertura da coleta de esgoto",
        "parcela da população atendida por coleta de esgoto.",
        "População atendida por coleta de esgoto ÷ população total × 100.",
        "%",
        polarity="higher",
    ),
    _proposed(
        17,
        "indice-perdas-distribuicao-agua",
        "Índice de perdas na distribuição de água",
        "parcela da água disponibilizada que não chega ao consumo autorizado.",
        "Volume de água perdido na distribuição ÷ volume de água disponibilizado × 100.",
        "%",
        polarity="lower",
    ),
    _proposed(
        17,
        "conformidade-amostras-qualidade-agua",
        "Conformidade das amostras de qualidade da água",
        "percentual de amostras que atende aos parâmetros de potabilidade aplicáveis.",
        "Amostras conformes ÷ amostras analisadas × 100, com detalhamento por parâmetro.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    # Eixo 18
    _proposed(
        18,
        "cobertura-arborea-area-urbana",
        "Cobertura arbórea da área urbana",
        "proporção da área urbana coberta por copa de árvores.",
        "Área de projeção de copas ÷ área urbana analisada × 100.",
        "%",
        polarity="higher",
    ),
    _proposed(
        18,
        "arvores-plantadas",
        "Árvores plantadas",
        "volume anual de plantios realizados ou coordenados pelo Município.",
        "Contagem dos plantios concluídos, com espécie, região e taxa de sobrevivência no detalhamento.",
        "árvores",
        polarity="higher",
    ),
    _proposed(
        18,
        "area-verde-por-habitante",
        "Área verde por habitante",
        "disponibilidade de áreas verdes públicas em relação à população.",
        "Área verde pública elegível ÷ população residente.",
        "m²/hab.",
        polarity="higher",
    ),
    _proposed(
        18,
        "area-recuperacao-ambiental",
        "Área em recuperação ambiental",
        "extensão de áreas com ações ativas de restauração ou recuperação.",
        "Somar a área com intervenção comprovada no período, evitando dupla contagem entre projetos.",
        "hectares",
        polarity="higher",
    ),
    # Eixo 19
    _proposed(
        19,
        "solicitacoes-abertura-empresas",
        "Solicitações de abertura de empresas",
        "demanda anual por abertura ou formalização empresarial.",
        "Contagem das solicitações protocoladas no período.",
        "solicitações",
        polarity="neutral",
    ),
    _proposed(
        19,
        "solicitacoes-abertura-empresas-deferidas",
        "Solicitações de abertura de empresas deferidas",
        "volume anual de solicitações de abertura que foram deferidas.",
        "Contagem das solicitações deferidas no período; acompanhar também a taxa sobre protocolos concluídos.",
        "solicitações",
        polarity="higher",
    ),
    _proposed(
        19,
        "empresas-ativas",
        "Empresas ativas",
        "estoque de empresas ativas no Município na data de referência.",
        "Contagem de registros empresariais ativos na data de corte anual.",
        "empresas",
        polarity="higher",
    ),
    _proposed(
        19,
        "meis-ativos",
        "Microempreendedores individuais ativos",
        "estoque de MEIs ativos no Município na data de referência.",
        "Contagem de registros de MEI ativos na data de corte anual.",
        "MEIs",
        polarity="higher",
    ),
    # Eixo 20
    _proposed(
        20,
        "servicos-municipais-digitais",
        "Serviços municipais disponíveis digitalmente",
        "parcela dos serviços municipais aptos a serem concluídos de forma digital.",
        "Serviços com jornada digital completa ÷ total de serviços catalogados × 100.",
        "%",
        polarity="higher",
    ),
    _proposed(
        20,
        "transacoes-servicos-digitais",
        "Participação das transações realizadas digitalmente",
        "uso efetivo dos canais digitais para serviços com alternativa presencial.",
        "Transações digitais concluídas ÷ total de transações elegíveis × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    _proposed(
        20,
        "disponibilidade-servicos-digitais",
        "Disponibilidade dos serviços digitais",
        "tempo em que os serviços digitais críticos permaneceram disponíveis.",
        "Tempo disponível ÷ tempo previsto de operação × 100, descontadas manutenções programadas homologadas.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    _proposed(
        20,
        "empresas-parque-tecnologico",
        "Empresas instaladas no Parque Tecnológico",
        "estoque de empresas presentes nos ambientes do Parque Tecnológico.",
        "Somar as empresas ativas nos ambientes do Parque, eliminando duplicidades entre ambientes.",
        "empresas",
        polarity="higher",
    ),
    # Eixo 21
    _proposed(
        21,
        "casos-violacao-direitos-atendidos",
        "Casos de violação de direitos atendidos",
        "proporção dos casos recebidos que tiveram atendimento ou encaminhamento registrado.",
        "Casos atendidos ou encaminhados ÷ casos recebidos × 100.",
        "%",
        polarity="higher",
        frequency="monthly",
    ),
    _proposed(
        21,
        "tempo-resposta-rede-protecao",
        "Tempo médio de resposta da rede de proteção",
        "tempo até o primeiro atendimento ou encaminhamento efetivo.",
        "Média dos dias entre registro do caso e primeiro atendimento ou encaminhamento.",
        "dias",
        polarity="lower",
        frequency="monthly",
    ),
    _proposed(
        21,
        "servicos-publicos-acessiveis",
        "Serviços públicos com acessibilidade verificada",
        "parcela dos serviços prioritários que atende aos critérios de acessibilidade homologados.",
        "Serviços prioritários conformes ÷ serviços prioritários avaliados × 100.",
        "%",
        polarity="higher",
    ),
    _proposed(
        21,
        "beneficiarios-programas-inclusao",
        "Pessoas atendidas por programas de inclusão",
        "participantes únicos dos programas municipais de inclusão.",
        "Contagem única de pessoas atendidas no período, com programa e público no detalhamento.",
        "pessoas",
        polarity="higher",
    ),
    # Eixo 22
    _proposed(
        22,
        "taxa-absenteismo-servidores",
        "Taxa de absenteísmo dos servidores",
        "proporção da jornada prevista não trabalhada por ausências consideradas na regra homologada.",
        "Horas de ausência elegíveis ÷ horas de trabalho previstas × 100.",
        "%",
        polarity="lower",
        frequency="monthly",
    ),
    _proposed(
        22,
        "horas-capacitacao-por-servidor",
        "Horas de capacitação por servidor",
        "intensidade média de desenvolvimento profissional da força de trabalho.",
        "Horas concluídas de capacitação ÷ servidores ativos médios no período.",
        "horas/servidor",
        polarity="higher",
    ),
    _proposed(
        22,
        "cobertura-avaliacao-desempenho-servidores",
        "Cobertura da avaliação de desempenho",
        "parcela dos servidores elegíveis com avaliação concluída no ciclo.",
        "Servidores avaliados ÷ servidores elegíveis × 100.",
        "%",
        polarity="higher",
    ),
    _proposed(
        22,
        "indice-satisfacao-servidores",
        "Índice de satisfação dos servidores",
        "resultado consolidado de pesquisa periódica de clima e satisfação.",
        "Aplicar instrumento padronizado e publicar escala, universo, amostra e taxa de resposta.",
        "pontos",
        polarity="higher",
    ),
)


SUPPLEMENTAL_INDICATORS = (
    _supplemental(
        1,
        "resultado-fiscal-consolidado-percentual",
        "Resultado fiscal consolidado",
        "Indicador complementar utilizado para reproduzir a série fiscal consolidada do relatório municipal.",
        "Preservar o percentual publicado pelo relatório, cuja metodologia utiliza receitas e despesas consolidadas.",
        "%",
        polarity="higher",
        source_name="Conjuntura Econômica 2025 — Prefeitura de São José do Rio Preto",
    ),
    _supplemental(
        4,
        "gasto-total-saude-por-habitante",
        "Gasto total em saúde por habitante",
        "Despesa total em saúde em relação à população municipal.",
        "Valor anual por habitante conforme série publicada no relatório municipal.",
        "R$/hab.",
        polarity="neutral",
        source_name="Conjuntura Econômica 2025 — Prefeitura de São José do Rio Preto",
    ),
    _supplemental(
        5,
        "familias-beneficiarias-bolsa-familia",
        "Famílias beneficiárias do Bolsa Família",
        "Indicador contextual do número de famílias beneficiárias no Município.",
        "Contagem de famílias beneficiárias na referência anual publicada.",
        "famílias",
        polarity="neutral",
        source_name="Conjuntura Econômica 2025 — Prefeitura de São José do Rio Preto",
    ),
    _supplemental(
        10,
        "residuos-domiciliares-coletados",
        "Resíduos domiciliares coletados",
        "Indicador complementar da produção física anual da coleta domiciliar.",
        "Somatório da massa de resíduos domiciliares coletada no período.",
        "toneladas",
        polarity="neutral",
        source_name="Conjuntura Econômica 2025 — Prefeitura de São José do Rio Preto",
    ),
    _supplemental(
        10,
        "extensao-varricao-diurna",
        "Extensão de varrição diurna",
        "Indicador complementar da produção física anual de varrição.",
        "Somatório dos quilômetros de vias atendidos pela varrição diurna no período.",
        "km",
        polarity="neutral",
        source_name="Conjuntura Econômica 2025 — Prefeitura de São José do Rio Preto",
    ),
    _supplemental(
        13,
        "total-alunos-rede-municipal",
        "Total de alunos da rede municipal",
        "Indicador contextual do universo de alunos atendidos pela rede municipal.",
        "Contagem de matrículas/alunos conforme referência utilizada pelo relatório municipal.",
        "alunos",
        polarity="neutral",
        source_name="Conjuntura Econômica 2025 — Prefeitura de São José do Rio Preto",
    ),
    _supplemental(
        14,
        "alunos-educacao-especial-atendidos",
        "Alunos da Educação Especial atendidos",
        "Indicador contextual do volume de alunos da Educação Especial atendidos.",
        "Contagem anual publicada no relatório municipal.",
        "alunos",
        polarity="neutral",
        source_name="Conjuntura Econômica 2025 — Prefeitura de São José do Rio Preto",
    ),
    _supplemental(
        16,
        "equipamentos-esportivos",
        "Equipamentos esportivos",
        "Indicador contextual do estoque de equipamentos esportivos municipais.",
        "Contagem de equipamentos na referência anual publicada.",
        "equipamentos",
        polarity="neutral",
        source_name="Conjuntura Econômica 2025 — Prefeitura de São José do Rio Preto",
    ),
    _supplemental(
        17,
        "volume-agua-tratada",
        "Volume de água tratada por dia",
        "Indicador complementar do volume médio diário de água tratada.",
        "Média diária do volume de água tratada no período, conforme série publicada.",
        "m³/dia",
        polarity="neutral",
        source_name="Conjuntura Econômica 2025 — Prefeitura de São José do Rio Preto",
    ),
    _supplemental(
        19,
        "exportacoes-valor-usd-fob",
        "Valor das exportações",
        "Indicador complementar do valor anual exportado pelo Município.",
        "Somatório anual do valor das exportações em dólares dos Estados Unidos, base FOB.",
        "US$ FOB",
        polarity="higher",
        source_name="Conjuntura Econômica 2025 — Prefeitura de São José do Rio Preto",
    ),
)


INDICATORS = MANDATORY_INDICATORS + PROPOSED_INDICATORS + SUPPLEMENTAL_INDICATORS


def _validate_catalog():
    dimension_slugs = [item["slug"] for item in DIMENSIONS]
    axis_numbers = [item["number"] for item in AXES]
    axis_slugs = [item["slug"] for item in AXES]
    indicator_slugs = [item["slug"] for item in INDICATORS]
    axis_dimension_by_number = {
        item["number"]: item["dimension_slug"] for item in AXES
    }

    assert len(DIMENSIONS) == 6
    assert len(set(dimension_slugs)) == len(dimension_slugs)
    assert axis_numbers == list(range(1, 23))
    assert len(set(axis_slugs)) == len(axis_slugs)
    assert all(item["dimension_slug"] in dimension_slugs for item in AXES)
    assert axis_dimension_by_number[17] == "cidade-que-se-transforma"
    assert axis_dimension_by_number[18] == "cidade-que-se-transforma"
    assert axis_dimension_by_number[19] == "cidade-que-gera-oportunidades"
    assert axis_dimension_by_number[20] == "cidade-que-funciona"
    assert axis_dimension_by_number[21] == "cidade-que-protege"
    assert axis_dimension_by_number[22] == "cidade-que-funciona"
    assert len(MANDATORY_INDICATORS) == 64
    assert all(
        sum(item["axis_number"] == axis_number for item in MANDATORY_INDICATORS) == 4
        for axis_number in range(1, 17)
    )
    assert len(PROPOSED_INDICATORS) == 24
    assert all(
        sum(item["axis_number"] == axis_number for item in PROPOSED_INDICATORS) == 4
        for axis_number in range(17, 23)
    )
    assert all(
        item["description"].startswith("Proposta técnica")
        and item["methodology"].startswith("Proposta técnica")
        for item in PROPOSED_INDICATORS
    )
    assert len(set(indicator_slugs)) == len(indicator_slugs)
    assert all(item["axis_number"] in axis_numbers for item in INDICATORS)
    assert all(len(item["name"]) <= 160 and len(item["slug"]) <= 180 for item in DIMENSIONS)
    assert all(len(item["name"]) <= 180 and len(item["slug"]) <= 200 for item in AXES)
    assert all(
        len(item["name"]) <= 240
        and len(item["slug"]) <= 260
        and len(item["unit"]) <= 40
        and len(item["source_name"]) <= 240
        for item in INDICATORS
    )


_validate_catalog()
